service: assignment-webtoon-server
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2
  memorySize: 1024
  profile: default
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
